#!/bin/bash
set -e

declare -a array
str=$(cut -d: -f1 /etc/passwd)

IFS=' ' # space is set as delimiter
read -ra ADDR <<< "$str" # str is read into an array as tokens separated by IFS
for i in "${ADDR[@]}"; do # access each element of array
    echo "$i"
done

for f in "${VAR1[@]}";
do

echo $f

echo "Delete? [y,n]"

read answer

if [[ answer == "y" ]]; then
  userdel $f
  echo "deleted"

else

if [[ /usr/bin/dscl . read /Groups/admin GroupMembership | /usr/bin/grep \- c $u == 1 ]] then 

/bin/echo "$u is in the admin group" 

echo "Would you like to remove? [y/n]"
read answer

if [ answer = "y" ] then
dseditgroup -o edit -d $f -t user admin

else 

/bin/echo "$u is not in the admin group" 
echo "Would you like to give access? [y/n]"
read answer

if [ answer = "y" ] then
sudo usermod -aG sudo <$f>

fi

fi

done
