#!/bin/bash
set -e

declare -a array
VAR1=$(cut -d: -f1 /etc/passwd)


for f in "${VAR1[@]}";
do

echo $f

echo "Delete? [y,n]"

read answer

if [[ answer == "y" ]]; then
  userdel $f
  echo "deleted"
fi

done
