#!/bin/bash
set -e

declare -a array
VAR1=$(cut -d: -f1 /etc/passwd)


for f in "${VAR1[@]}";
do

echo $f

echo "Delete? [y,n]"

read answer

if [[ answer == "y" ]]; then
  userdel $f
  echo "deleted"

else

if [[ /usr/bin/dscl . read /Groups/admin GroupMembership | /usr/bin/grep \- c $u == 1 ]] then 

/bin/echo "$u is in the admin group" 

echo "Would you like to remove? [y/n]"
read answer

if [ answer = "y" ] then
dseditgroup -o edit -d $f -t user admin

else 

/bin/echo "$u is not in the admin group" 
echo "Would you like to give access? [y/n]"
read answer

if [ answer = "y" ] then
sudo usermod -aG sudo <$f>

fi

fi

done
