#!/bin/bash
set -e

declare -a array
shopt -s nullglob

for f in /home/*/*/*;
do

echo $f
if [[ $f = *malware* ]]; then
echo "yes"
array+=($f)
fi

if [[ $f = *delete* ]]; then
array+=($f)
fi

if [[ $f = *phis* ]]; then
array+=($f)
fi

if [[ $f = *virus* ]]; then
array+=($f)
fi

done




for virus in "${array[@]}";
do

echo $(basename "$virus")
echo
echo "Delete? [y,n]"

read answer

if [[ $answer == "y" ]]; then
  rm $virus
  echo "deleted"
fi

echo "${array[*]}"
done
