#!/bin/bash
set -e

array = ()
arr=(~/myDir/*)

for f in "${arr[@]}"; 
do

if grep -q malware "$f";  then
array += ($f)
fi

if grep -q delete "$f"; then
array += ($f)
fi

if grep -q phis "$f"; then
array += ($f)
fi

done

for virus in "${array[@]}";
do

echo $(basename "$virus")

echo "Delete? [Y,n]"
read answer

if ["answer"="y"]; then
  rm $virus
fi

done

